[package]
name = "trace-preprocess"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
clap = { version = "4.5", features = ["derive"] }
