# Yahoo! Cloud System Benchmark
# Workload A: Update heavy workload
#   Application example: Session store recording recent actions
#                        
#   Read/update ratio: 50/50
#   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
#   Request distribution: zipfian

name = "YCSB-A (50M)"
value_size = 1024
count = 50_000_000
duration = 60

[distribution]
zipf = 0.99

[proportion]
insert = 0
read = 0.5
update = 0.5
